-- Missing table in old DB: SS
CREATE TABLE SS (
    DATA_INTR DATE DEFAULT NULL,
    TIP_DOC VARCHAR(2),
    GESTIUNE VARCHAR(4) DEFAULT '',
    DEN_GEST VARCHAR(100) DEFAULT '',
    COD_ART VARCHAR(16) DEFAULT '',
    COD_CLI VARCHAR(8) DEFAULT '',
    COD_FUR VARCHAR(8) DEFAULT '',
    PRET_VANZ NUMERIC(16,4) DEFAULT 0,
    PRET_MEDIU NUMERIC(16,4) DEFAULT 0,
    LOT VARCHAR(24) DEFAULT '',
    DENUMIRE VARCHAR(100) DEFAULT '',
    TIP VARCHAR(2) DEFAULT '',
    DEN_TIP VARCHAR(100) DEFAULT '',
    UM VARCHAR(5) DEFAULT '',
    GRUPA VARCHAR(16) DEFAULT '',
    TVA NUMERIC(5,2) DEFAULT 0,
    CANT_MIN NUMERIC(14,3) DEFAULT 0,
    GREUTATE NUMERIC(14,3) DEFAULT 0,
    CONT VARCHAR(20) DEFAULT '',
    VANDABIL SMALLINT DEFAULT 0,
    GARANTIE DATE DEFAULT NULL,
    TEXT_SUPL VARCHAR(250) DEFAULT '',
    CANT_INIT NUMERIC(14,3) DEFAULT 0,
    VAL_INIT NUMERIC(15,2) DEFAULT 0,
    VAL_INT NUMERIC(15,2) DEFAULT 0,
    VAL_IES NUMERIC(15,2) DEFAULT 0,
    CANT_INT NUMERIC(14,3) DEFAULT 0,
    CANT_IES NUMERIC(14,3) DEFAULT 0,
    INF_LOT VARCHAR(120) DEFAULT '',
    PK INTEGER NOT NULL,
    CONSTRAINT PK_SS PRIMARY KEY (PK)
);
-- Deleted table in new DB: SAFT_CLIENTI (consider dropping or logging)
-- Deleted table in new DB: SAFT_FURNIZORI (consider dropping or logging)
ALTER TABLE CONFIGURARE_UBC ADD DATA_S DATE;
ALTER TABLE CONFIGURARE_UBC ADD DATA_I DATE;
ALTER TABLE CONFIGURARE_UBC ADD IS_WEB SMALLINT DEFAULT 0;
ALTER TABLE S_C_MI ADD COD_FUR VARCHAR(8) DEFAULT '';
ALTER TABLE S_C_MI ADD COD_CLI VARCHAR(8) DEFAULT '';
ALTER TABLE S_C_RULAJ_NEGATIV ADD COD_FUR VARCHAR(8) DEFAULT '';
ALTER TABLE S_C_RULAJ_NEGATIV ADD COD_CLI VARCHAR(8) DEFAULT '';
ALTER TABLE CD ADD LAST_USED SMALLINT DEFAULT 0;
ALTER TABLE S_C_INIT ADD COD_FUR VARCHAR(8) DEFAULT '';
ALTER TABLE S_C_INIT ADD COD_CLI VARCHAR(8) DEFAULT '';
ALTER TABLE S_C_RULAJ ADD COD_FUR VARCHAR(8) DEFAULT '';
ALTER TABLE S_C_RULAJ ADD COD_CLI VARCHAR(8) DEFAULT '';